version: '3.8'
services:
  webapp:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://db:3306
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=dev1234*
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=webapp
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
      - ./sql/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
  mysql_config:
