version: '3.8'
services:
  db:
    image: custom-mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=webapp
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

      # The following doesn't work on Windows.
      #- ./sql/init:/docker-entrypoint-initdb.d

      # So, I have to create a custom MySQL image,
      # > docker build -f Dockerfile -t custom-mysql:latest .

volumes:
  mysql_data:
  mysql_config:
